### ISSUE TITLE
Different target schema for custom events

### ISSUE THREAD

**Issue by autopoiesis3004** [ArtemKorneevGA/dataform-ga4-sessions#1]
Hi Artem,

I am new to using Dataform and struggling to define different a target schema when I use the event factory to create a table with several custom events at once:

const ef = new ga4.EventFactory(config);
let events = ef.createEvents(custom_events.config);
events.forEach((event) => 
event.publish());

I tried to apply the dataformAction.target method without success. Data is always written to the standard dataform_staging schema. Is it also possible to change the target schema / tablename in this scenario?

**Comment by ArtemKorneevGA** [comment]
Thanks for the feedback!

You could change schema like this:
```
const ef = new ga4.EventFactory(config);
const events = ef.createEcommerceEvents();
events.forEach((event) => {
//change target schema
    event.target.schema = "my_schema";
    event.publish()
}
);
```
But also starting from version **1.0.5** it's possible to use [targetSchema](https://artemkorneevga.github.io/dataform-ga4-sessions/events/event-factory#change-target-schema-for-all-events):
```
// Define EventFactory
const ef = new ga4.EventFactory(eventConfig);
// Set target schema for all events created by factory
ef.targetSchema = "my_schema";
let events = ef.createEcommerceEvents();
events.forEach((event) => {
  // But you could overwrite target schema for particular event
  if (event.target.tableName === "purchase") {
    event.target.schema = " my_schema_2";
  }
  event.publish();
});
```
But to use targetSchema you need to update package version to at least **1.0.5**

**Comment by autopoiesis3004** [comment]
Thanks a lot  - works like a charm :-)
